version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/angular-app"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/angular-http-hard-way"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/svelte-app"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
